### ISSUE TITLE
`suggest` fails with TypeError: Cannot read property 'pretty' of undefined

### ISSUE THREAD

**Issue by ginkel** [hallh/elasticsearch-primary-balancer#3]
When running `node balance.js suggest` (current Git master), the following exception is emitted:

```
/home/tg/src/elasticsearch-primary-balancer/balance.js:201
  return `[+] Suggested move:\n${play.pretty()}\n\ncurl '${args.host}/_cluster/reroute' -X POST -H 'Content-Type: application/json' -d '${play.commands()}'\n`;
                                      ^

TypeError: Cannot read property 'pretty' of undefined
    at decideSuggestResult (/home/tg/src/elasticsearch-primary-balancer/balance.js:201:39)
    at decideResult (/home/tg/src/elasticsearch-primary-balancer/balance.js:177:12)
    at run (/home/tg/src/elasticsearch-primary-balancer/balance.js:96:15)
    at /home/tg/src/elasticsearch-primary-balancer/balance.js:39:5
    at IncomingMessage.<anonymous> (/home/tg/src/elasticsearch-primary-balancer/src/http.js:96:9)
```

**Comment by hallh** [comment]
The `play` object will typically only be undefined if no move is possible. I just tested with a large number of indexes and a short simulation time, but that case is handled correctly with a proper error message. So in this case, my first guess would be that the simulation time was high enough, but no moves were possible.

Could you share some details about the number of nodes, indexes and the shard + replica count of the indexes. Will be helpful in order to figure out what may be going wrong.

**Comment by ginkel** [comment]
That makes sense. When running with `dry-run` I actually get no permitted moves:

```
$ node balance.js dry-run --auth <secret> --index index1,index2 --simulation-time 60  https://data1.domain:9200


[-] No threshold specified, will try to achieve a perfect balance.

[+] Using threshold: 0.500
[+] Simulation time: 60 seconds.

[+] Current cluster state:
 data1.domain:        0       (0.000)
 data2.domain:  10      (1.000)


[!] Impossible to achieve desired balance, try a higher threshold.
```

I have a three-node cluster. One node is master-only, the two other nodes are master- and data-enabled. index1 and index2 both have 5 primary and 5 replica shards. All primary shards reside on node data2, all replica shards on data1 (as a result of a rolling update).

```
index1                4 p STARTED  532.9mb data2
index1                4 r STARTED    350mb data1
index1                1 p STARTED    390mb data2
index1                1 r STARTED  360.6mb data1
index1                3 p STARTED  660.8mb data2
index1                3 r STARTED  346.2mb data1
index1                2 p STARTED  490.9mb data2
index1                2 r STARTED  327.7mb data1
index1                0 p STARTED  334.4mb data2
index1                0 r STARTED  337.4mb data1
```

IMHO it should be possible to distribute primaries and secondaries across both nodes.

Any idea?

**Comment by hallh** [comment]
ES doesn't allow to move a shard to a node where a replica already exists. With your current setup, the two nodes will always mirror each other (each node having exactly one replica of each shard), so it's not possible to move any shards around and do the balancing.

Currently there's no way to promote a specific shard to be a primary, hence this tool. The promotion only happens if a node hosting a primary goes down. In your case it means that any time one of your data nodes goes down, all the replicas on the other node will be promoted to primaries. Leaving you with all your primaries on the same node.

You'll need to add a third node to do the balancing.

**Comment by ginkel** [comment]
That makes sense, thanks for the speedy reply! :-)
